<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Projects</title>

<script src="site_libs/header-attrs-2.30/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/cosmo.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>









<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">My Website</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
<li>
  <a href="about.html">About</a>
</li>
<li>
  <a href="projects.html">Projects</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">Projects</h1>

</div>


<p>Below are two example projects from my coursework that use R for
business analytics and data exploration.</p>
<div id="project-1-regional-sales-performance-analysis"
class="section level2">
<h2>Project 1: Regional Sales Performance Analysis</h2>
<p>In this project, I created a sample regional_sales dataset to
practice business analytics. The data tracks revenue and customers
across four regions (North, South, East, West) and four quarters. I used
R to inspect the structure, summarize key metrics, and identify high-
and low-performing regions and periods.</p>
<p>Key Skills Demonstrated:</p>
<p>-Creating and working with data frames in R</p>
<p>-Using functions like str(), summary(), unique(), and aggregate()</p>
<p>-Identifying high-performing regions and quarters based on revenue
and customers</p>
<p>-Calculating total and average values to support business
insights</p>
<p>-Explaining results in clear, business-focused language</p>
<hr />
<p>Create sample regional sales data</p>
<pre class="r"><code>regional_sales &lt;- data.frame(
  region = c(&quot;North&quot;, &quot;South&quot;, &quot;East&quot;, &quot;West&quot;, &quot;North&quot;, &quot;South&quot;, &quot;East&quot;, &quot;West&quot;,
             &quot;North&quot;, &quot;South&quot;, &quot;East&quot;, &quot;West&quot;, &quot;North&quot;, &quot;South&quot;, &quot;East&quot;, 
             &quot;North&quot;, &quot;South&quot;,&quot;North&quot;),  
  quarter = c(rep(c(&quot;Q1&quot;, &quot;Q2&quot;, &quot;Q3&quot;, &quot;Q4&quot;), each = 4), &quot;Q4&quot;, &quot;Q4&quot;),
  revenue = c(125000, 98000, 115000, 102000, 
              138000, 105000, 128000, 118000,
              142000, 89000, 135000, 125000,
              155000, 112000, 148000, 165000, 
              120000, 91250),
  customers = c(450, 380, 420, 395, 
                485, 415, 465, 445,
                520, 350, 485, 470,
                575, 425, 545, 590, 435,324)
)</code></pre>
</div>
<div id="data-import-and-exploration-question-1-content"
class="section level1">
<h1>Data Import and Exploration (Question 1 content)</h1>
<div id="a" class="section level2">
<h2>A)</h2>
<pre class="r"><code>str(regional_sales)</code></pre>
<pre><code>## &#39;data.frame&#39;:    18 obs. of  4 variables:
##  $ region   : chr  &quot;North&quot; &quot;South&quot; &quot;East&quot; &quot;West&quot; ...
##  $ quarter  : chr  &quot;Q1&quot; &quot;Q1&quot; &quot;Q1&quot; &quot;Q1&quot; ...
##  $ revenue  : num  125000 98000 115000 102000 138000 105000 128000 118000 142000 89000 ...
##  $ customers: num  450 380 420 395 485 415 465 445 520 350 ...</code></pre>
<p>Number of observations: 18</p>
<p>Number of variables: 4</p>
<p>Variables and data types of each variable: region, Character (chr),
Region name (e.g., “North”, “South”) quarter, Character (chr), Quarter
of the year (e.g., “Q1”, “Q2”) revenue, Numeric (num), Revenue in
dollars customers, Numeric (num), Number of customers</p>
</div>
<div id="b" class="section level2">
<h2>B)</h2>
<pre class="r"><code>summary(regional_sales)</code></pre>
<pre><code>##     region            quarter             revenue         customers    
##  Length:18          Length:18          Min.   : 89000   Min.   :324.0  
##  Class :character   Class :character   1st Qu.:106750   1st Qu.:416.2  
##  Mode  :character   Mode  :character   Median :122500   Median :447.5  
##                                        Mean   :122847   Mean   :454.1  
##                                        3rd Qu.:137250   3rd Qu.:485.0  
##                                        Max.   :165000   Max.   :590.0</code></pre>
<p>Range of revenue: $89,000 - $165,000</p>
<pre class="r"><code>head(regional_sales)</code></pre>
<pre><code>##   region quarter revenue customers
## 1  North      Q1  125000       450
## 2  South      Q1   98000       380
## 3   East      Q1  115000       420
## 4   West      Q1  102000       395
## 5  North      Q2  138000       485
## 6  South      Q2  105000       415</code></pre>
<p>Regions in the first few rows: North, South, East, West</p>
</div>
<div id="c" class="section level2">
<h2>C)</h2>
<pre class="r"><code>unique(regional_sales$region)</code></pre>
<pre><code>## [1] &quot;North&quot; &quot;South&quot; &quot;East&quot;  &quot;West&quot;</code></pre>
<pre class="r"><code>unique(regional_sales$quarter)</code></pre>
<pre><code>## [1] &quot;Q1&quot; &quot;Q2&quot; &quot;Q3&quot; &quot;Q4&quot;</code></pre>
<p>4 Regions (North, South, East, West) 4 Quarters (Q1. Q2, Q3, Q4)</p>
</div>
<div id="d" class="section level2">
<h2>D)</h2>
<pre class="r"><code> sum(regional_sales$customers)</code></pre>
<pre><code>## [1] 8174</code></pre>
<p>This total shows that across all regions and quarters, the business
served 8,674 customers in total.This reflects overall customer
engagement or market reach during the reporting period. Comparing this
number with total revenue could show an average revenue per customer,
helping assess customer value and efficiency. Tracking this total over
time can also show growth trends in customer base and help identify
strong-performing regions or quarters.</p>
</div>
</div>
<div id="data-quality-assessment-question-2-content"
class="section level1">
<h1>Data Quality Assessment (Question 2 content)</h1>
<div id="a-1" class="section level2">
<h2>A)</h2>
<pre class="r"><code>sum(is.na(regional_sales))</code></pre>
<pre><code>## [1] 0</code></pre>
<p>There are no missing values in the dataset. In a real business
scenario missing values can lead to incorrect calculations causing data
inaccuracy. It can be misleading because having missing values would be
an incomplete dataset. Also identifying missing data early helps to
decide whether to remove or investigate the cause.</p>
</div>
<div id="b-1" class="section level2">
<h2>B)</h2>
<pre class="r"><code>table(regional_sales$region)</code></pre>
<pre><code>## 
##  East North South  West 
##     4     6     5     3</code></pre>
<pre class="r"><code>table(regional_sales$quarter)</code></pre>
<pre><code>## 
## Q1 Q2 Q3 Q4 
##  4  4  4  6</code></pre>
<p>The data is not evenly distributed across regions or quarters. The
North appears six times, while the West appears only three times. Q4 has
six records, compared to four in each of the other quarters. This
suggests the North is probably the busiest region, and the West may have
fewer sales or less reporting. Q4 might be busier because it falls at
the end of the year, during the holidays. Since the data is uneven, it
could affect the results. Regions or quarters with more data might make
the numbers seem higher or lower than they actually are.</p>
</div>
<div id="c-1" class="section level2">
<h2>C)</h2>
<pre class="r"><code>regional_sales[regional_sales$revenue &lt; 90000, ]</code></pre>
<pre><code>##    region quarter revenue customers
## 10  South      Q3   89000       350</code></pre>
<p>South Region Q3 shows 89000 revenue and 350 customers.</p>
</div>
</div>
<div id="business-logic-analysis-question-3-content"
class="section level1">
<h1>Business Logic Analysis (Question 3 content)</h1>
<div id="a-2" class="section level2">
<h2>A)</h2>
<pre class="r"><code>regional_sales[regional_sales$revenue &gt; 140000, ]</code></pre>
<pre><code>##    region quarter revenue customers
## 9   North      Q3  142000       520
## 13  North      Q4  155000       575
## 15   East      Q4  148000       545
## 16  North      Q4  165000       590</code></pre>
<pre class="r"><code>high_perf &lt;- regional_sales[regional_sales$revenue &gt; 140000, ]

nrow(high_perf)</code></pre>
<pre><code>## [1] 4</code></pre>
<p>Regions North and East achieved high performance.There are 4
high-performance records.</p>
</div>
<div id="b-2" class="section level2">
<h2>B)</h2>
<pre class="r"><code>regional_sales[regional_sales$quarter == &quot;Q4&quot; &amp; 
               regional_sales$revenue &gt; 130000 &amp; 
               regional_sales$customers &gt; 500, ]</code></pre>
<pre><code>##    region quarter revenue customers
## 13  North      Q4  155000       575
## 15   East      Q4  148000       545
## 16  North      Q4  165000       590</code></pre>
<p>This combination suggests that year-end sales were particularly
strong in certain regions. This could be due to seasonal demand (e.g.,
holidays or promotions), effective regional strategies or marketing, or
strong customer engagement and retention.</p>
</div>
<div id="c-2" class="section level2">
<h2>C)</h2>
<pre class="r"><code># Filter for North OR East regions
north_east &lt;- regional_sales[regional_sales$region == &quot;North&quot; | 
                             regional_sales$region == &quot;East&quot;, ]

# Calculate average revenue for North and East
mean_NE &lt;- mean(north_east$revenue)

# Calculate overall average revenue
mean_all &lt;- mean(regional_sales$revenue)

# Display both results
mean_NE</code></pre>
<pre><code>## [1] 134225</code></pre>
<pre class="r"><code>mean_all</code></pre>
<pre><code>## [1] 122847.2</code></pre>
<p>The average revenue for the North and East regions ($134,225) is
higher than the overall average revenue ($122,847.20). The North and
East regions are performing above average, bringing in more sales than
the company’s average performance.</p>
</div>
<div id="d-1" class="section level2">
<h2>D)</h2>
<pre class="r"><code># Create a performance flag
regional_sales$low_perf &lt;- regional_sales$revenue &lt; 100000 | 
                           regional_sales$customers &lt; 400

# Count how many records are flagged
sum_low &lt;- sum(regional_sales$low_perf)

# Calculate the percentage of total records
perc_low &lt;- (sum_low / nrow(regional_sales)) * 100

# Display both results
sum_low</code></pre>
<pre><code>## [1] 4</code></pre>
<pre class="r"><code>perc_low</code></pre>
<pre><code>## [1] 22.22222</code></pre>
<p>Number of concerning records: 4</p>
<p>Percentage of total records: 22.22%</p>
</div>
</div>
<div id="data-aggregation-and-business-insights-question-4-content"
class="section level1">
<h1>Data Aggregation and Business Insights (Question 4 content)</h1>
<div id="a-3" class="section level2">
<h2>A)</h2>
<pre class="r"><code># Calculate total revenue by region
total_rev_by_region &lt;- aggregate(revenue ~ region, data = regional_sales, sum)

# Display results
total_rev_by_region</code></pre>
<pre><code>##   region revenue
## 1   East  526000
## 2  North  816250
## 3  South  524000
## 4   West  345000</code></pre>
<p>The North region generated the highest total revenue.</p>
</div>
<div id="b-3" class="section level2">
<h2>B)</h2>
<pre class="r"><code># Calculate average customers by quarter
avg_customers_by_quarter &lt;- aggregate(customers ~ quarter, data = regional_sales, mean)

# Display results
avg_customers_by_quarter</code></pre>
<pre><code>##   quarter customers
## 1      Q1  411.2500
## 2      Q2  452.5000
## 3      Q3  456.2500
## 4      Q4  482.3333</code></pre>
<p>Q4 has the highest average customer count, meaning people are buying
more at the end of the year. This typically happens because of the
holidays and year end sales promotions.</p>
</div>
</div>
<div id="executive-summary-creation-question-5-content"
class="section level1">
<h1>Executive Summary Creation (Question 5 content)</h1>
<div id="a-4" class="section level2">
<h2>A)</h2>
<pre class="r"><code># Total revenue across all regions and quarters
total_revenue &lt;- sum(regional_sales$revenue)

# Average revenue per quarter
avg_rev_per_quarter &lt;- aggregate(revenue ~ quarter, data = regional_sales, mean)

# Number of high-performance records (revenue &gt; $140,000)
high_perf_count &lt;- sum(regional_sales$revenue &gt; 140000)

# Display results
total_revenue</code></pre>
<pre><code>## [1] 2211250</code></pre>
<pre class="r"><code>avg_rev_per_quarter</code></pre>
<pre><code>##   quarter revenue
## 1      Q1  110000
## 2      Q2  122250
## 3      Q3  122750
## 4      Q4  131875</code></pre>
<pre class="r"><code>high_perf_count</code></pre>
<pre><code>## [1] 4</code></pre>
</div>
<div id="b-4" class="section level2">
<h2>B)</h2>
<p>The analysis shows that the North region has the most reliable
performance, bringing in the highest total revenue of $816,250 for the
year and staying strong each quarter. The West and South regions have
lower and less steady results. The fourth quarter stands out with the
highest average revenue of $159,750 and the largest average customer
base of about 484. These results suggest the company could benefit from
using the strategies that work well in Q4 throughout the year and
applying the North region’s steady approach to help other regions
improve.</p>
</div>
</div>
<div
id="project-2-introduction-to-e-business-analytics-performance-metrics-report"
class="section level1">
<h1>Project 2: Introduction to E-Business Analytics – Performance
Metrics Report</h1>
<p>This project uses a custom webperfo dataset based on the built-in
airquality data in R. I treated variables as engagement, website
performance, and server load to explore how user engagement relates to
technical performance. I created scatterplots, added titles and labels,
and included a trend line to support business interpretation.</p>
<p>Key Skills Demonstrated:</p>
<p>-Creating derived datasets in R from existing data</p>
<p>-Using head(), summary(), nrow(), max(), and cor() for
exploration</p>
<p>-Building and improving scatterplots for business presentations</p>
<p>-Adding regression lines and interpreting correlations</p>
<p>-Translating statistical findings into recommendations for e-business
managers</p>
</div>
<div id="executive-summary" class="section level1">
<h1>Executive Summary</h1>
<p>This report analyzes the relationship between user engagement and
website performance. The data shown suggests a moderately positive
correlation between user engagement and website performance. This
suggests that engaged users are more likely to interact with a
responsive and efficient website. For e-business managers, this insight
highlights the value of optimizing both user experience and back-end
performance to drive better outcomes.</p>
</div>
<div id="website-performance-analysis" class="section level1">
<h1>Website Performance Analysis</h1>
</div>
<div id="create-website-performance-dataset-with-business-terminology"
class="section level1">
<h1>Create website performance dataset with business terminology</h1>
<pre class="r"><code>webperfo &lt;- data.frame(
  engagement = airquality$Temp,
  performance = airquality$Ozone,
  server_load = airquality$Wind
)
head(webperfo)</code></pre>
<pre><code>##   engagement performance server_load
## 1         67          41         7.4
## 2         72          36         8.0
## 3         74          12        12.6
## 4         62          18        11.5
## 5         56          NA        14.3
## 6         66          28        14.9</code></pre>
<p>A)There is 3 columns of data. Names are engagement, performance, and
server_load. It is useful to see the first few rows because it gives a
quick overview rather than a large amount all at once. It would be
helpful and more efficient with larger data sets to be able to spot
missing values or data issues early.</p>
<pre class="r"><code>summary(webperfo)</code></pre>
<pre><code>##    engagement     performance      server_load    
##  Min.   :56.00   Min.   :  1.00   Min.   : 1.700  
##  1st Qu.:72.00   1st Qu.: 18.00   1st Qu.: 7.400  
##  Median :79.00   Median : 31.50   Median : 9.700  
##  Mean   :77.88   Mean   : 42.13   Mean   : 9.958  
##  3rd Qu.:85.00   3rd Qu.: 63.25   3rd Qu.:11.500  
##  Max.   :97.00   Max.   :168.00   Max.   :20.700  
##                  NA&#39;s   :37</code></pre>
<p>B)Performace has 37 missing values (NA37). The minimum engagement
score is 56, and the maximum is 97. So the range of engagement scores is
56 to 97.</p>
<pre class="r"><code>nrow(webperfo)</code></pre>
<pre><code>## [1] 153</code></pre>
<p>C)It shows how much historical data they have to use. It can help
with identifying seasonal trends or weekly patterns in engagement and
performace. The more data that is available the more accurate analysis,
forecast, or improvement plans will be.</p>
<pre class="r"><code>max(webperfo$engagement)</code></pre>
<pre><code>## [1] 97</code></pre>
<p>D)The max engagement is 97, whereas the median is 79. This shows that
there were a few very high engagement days, but overall most days show a
lower engagement closer to the median.</p>
<pre class="r"><code>max(webperfo$performance, na.rm = TRUE)</code></pre>
<pre><code>## [1] 168</code></pre>
<p>E)The performance column has missing values, without adding na.rm =
true R will return NA because it cant calculate the max with the missing
data present. The engagement column had no missing values so not
including na.rm = true did not matter.</p>
</div>
<div id="understanding-relationships" class="section level1">
<h1>Understanding Relationships</h1>
<pre class="r"><code>plot(webperfo$engagement, webperfo$performance)</code></pre>
<p><img src="projects_files/figure-html/unnamed-chunk-22-1.png" width="672" /></p>
<p>A)It shows as engagement increases performance increases, however it
is not strong, it is hard to clearly see. For a business presentation it
would need a title, x and y axis labels, and a defined axes.</p>
<pre class="r"><code>plot(x = webperfo$engagement, y = webperfo$performance,
     main = &quot;User Engagement vs Website Performance&quot;,
     xlab = &quot;Daily User Engagement Score&quot;, 
     ylab = &quot;Website Performance Score&quot;,
     pch = 16)</code></pre>
<p><img src="projects_files/figure-html/unnamed-chunk-23-1.png" width="672" /></p>
<p>B)The title defines what the information is about, and the axis
labels translates raw variable names into business friendly terms.</p>
<pre class="r"><code>plot(x = webperfo$engagement, y = webperfo$performance,
     main = &quot;User Engagement vs Website Performance&quot;,
     xlab = &quot;Daily User Engagement Score&quot;, 
     ylab = &quot;Website Performance Score&quot;,
     pch = 16,
     col = &quot;blue&quot;)</code></pre>
<p><img src="projects_files/figure-html/unnamed-chunk-24-1.png" width="672" /></p>
<p>C)This plot shows a positive relationship between user engagement and
website performance. It suggests that on days when users are more
engaged and interacting with the website content, the overall
performance of the website also improves. This could mean higher
conversion rates, lower bounce rates, or increased revenue.</p>
<pre class="r"><code>plot(x = webperfo$engagement, y = webperfo$performance,
     main = &quot;User Engagement vs Website Performance&quot;,
     xlab = &quot;Daily User Engagement Score&quot;, 
     ylab = &quot;Website Performance Score&quot;,
     pch = 16,
     col = &quot;blue&quot;)
     abline(lm(performance ~ engagement, data = webperfo), 
       col = &quot;red&quot;, lwd = 2)</code></pre>
<p><img src="projects_files/figure-html/unnamed-chunk-25-1.png" width="672" /></p>
<p>D)The red line is going up, showing a positive trend for website
performance as engagement increases.</p>
</div>
<div id="business-interpretation" class="section level1">
<h1>Business Interpretation</h1>
<pre class="r"><code>cor(webperfo$engagement, webperfo$performance, use = &quot;complete.obs&quot;)</code></pre>
<pre><code>## [1] 0.6983603</code></pre>
<p>A)The correlation coefficient is aprox 0.698 which is a moderately
strong (0.3-0.7) relationship</p>
<p>B)When engagement is high the website performance improves. The
information shown should aid an e-business manager to be investing in
engagement strategies to support better performance outcomes. This could
include features that support longer user interaction, as it is shown to
be linked to overall success.</p>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
